name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Type check
        run: npm run typecheck

      - name: 🧹 Lint check
        run: npx eslint . --ext .ts,.tsx

      - name: 🔧 Build app
        run: npm run build 